/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package projet1;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static int addition(final int x, final int y) {
        return x+y+1;
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
